apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: employee-backend

  template:
    metadata:
      labels:
        app: employee-backend

    spec:
      containers:
      - name: backend
        image: kpunteethg/employee-backend:latest

        imagePullPolicy: Never

        ports:
        - containerPort: 5000
