apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
    spec:
      containers:
        - name: frontend
          image: kpunteethg/employee-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
